### ISSUE TITLE
Broken link in kerhoilta-16-5-minitesla

### ISSUE THREAD

**Issue by zouppen** [HacklabJKL/website#1]
https://uusi.jyvaskyla.hacklab.fi/2017/05/16/kerhoilta-16-5-minitesla/ tuolla oleva linkki "aiemminkin 
                nähty" ei toimi

**Comment by flannelhead** [comment]
Korjattu tämä ja yksi toinenkin rikkinäinen suhteellinen linkki blogipostauksista. Muita en ainakaan greppaamalla löytänyt.
