### ISSUE TITLE
Jäsenrekisterin rekisteriseloste puuttuu

### ISSUE THREAD

**Issue by jssmk** [HacklabJKL/website#2]
Erityishuomiona: tallennetaanko myönnettyjen alennusten perustelut osana jäsenrekisterin tietoja?

**Comment by BFlorry** [comment]
Ei tallenneta, ellei hakemuksesta lähtevää sähköpostia lasketa sellaiseksi.

**Comment by zouppen** [comment]
Näitä voi editoida:

* Suomeksi: https://uusi.jyvaskyla.hacklab.fi/en/association/privacy-policy/
* Englanniksi: https://uusi.jyvaskyla.hacklab.fi/en/association/privacy-policy/

Englanniksi ei tartte olla tarkka juridisten termien kanssa koska Suomen laki määrittelee tuon vain suomeksi ja se on lain vaatima. Enkkuversiossa voi sanoa että ei autoritatiivinen vaan ohjeellinen käännös suomenkielisestä.

**Comment by flannelhead** [comment]
Rekisteriseloste ja Privacy Policy katselmointia vaille done.

**Comment by zouppen** [comment]
Jooh menköön noin. Nuo salausjutut on vähän höpsöjä. Meillä on nyt Git-repo joka on omalla palvelimella eli tavallaan totta, joten annan olla noin. Tuotantoon meni.
