### ISSUE TITLE
Sähköpostiosoitteiden obfuskointi

### ISSUE THREAD

**Issue by PetteriAimonen** [HacklabJKL/website#3]
Sähköpostiosoitteet olisi hyvä jotenkin piilottaa jotta spammibotit eivät kerää niitä.

Esim. tämä javascript-kikka toimii aika hyvin:
https://www.kapsi.fi/yhdistys/yhteystiedot.html
https://www.kapsi.fi/roskaposti.js

Tai sitten css-kikka joka on vanhoilla sivuilla.

**Comment by zouppen** [comment]
Pitäiskö sama tehdä puhelinnumerolinkeille? Kunhan toimii androidissa klikkaamalla niin ok.

**Comment by zouppen** [comment]
Sähköposti on obfuskoitu nyt Kapsi-tekniikalla. Yhdestä paikasta löytyi vaan eli tuo hallitus@
