### ISSUE TITLE
Uusi jäsen -lomakkeen viimeistely

### ISSUE THREAD

**Issue by zouppen** [HacklabJKL/website#4]
Uuden jäsenen lomakkeeseen kaikki kentät kuntoon, Javascripti vanhalta sivulta ja käännös englanniksi.

**Comment by zouppen** [comment]
Kohtuullisen kammottava Javaskripti laitettu kohdilleen ja muokattu tekstiä. Sähköpostin sisältö ja enkkukäännös vielä tekemättä.

**Comment by zouppen** [comment]
Javaskriptit siirretty eilen headeriin, jossa on myös kävijäseurantaskripti. Lomake on siis kosher eikä sen kääntämisessä tarvitse huomioida muuta kuin että "jasenyys" id:tä ei saa kääntää. Sisällön toki.

**Comment by BFlorry** [comment]
Lomakkeessa on tagi Reply-To [your-email], jonka pitäisi laittaa vastaustahoksi lomakkeen lähettäjä, mutta jostain syystä näin ei tapahdu ainakaan gmailissa.

**Comment by zouppen** [comment]
Eiks se voi olla vaan from? Voidaan tehdä loputtomasti aliaksia, tyyliin jasenasiat@jkl.hacklab*, joka ohjaa haluttuun osoitteeseen tai hallitus@jkl.hacklab*

**Comment by BFlorry** [comment]
Meinaan siis kun Pekka Penkkipunnertaja haluaa liittyä jäseneksi ja hänen sähköpostiosoitteensa on pekka@penkkipunnertaja.fi, niin silloin Reply-To:hon menisi automaattisesti tuo em. sähköpostiosoite. Kun sähköposti saapuu hallituslistalle, niin sitten sähköpostiohjelma automaattisesti ehdottaisi vastattaessa vastaustahoksi pekka@penkki... lomakesähköpostin sijaan.

**Comment by zouppen** [comment]
Laitoin toimimaan. Huomaa tuo lähettäjän sähköposti; vaikka tulee seuraava varoitus:

> Sender email address does not belong to the site domain.

Niin tuo on oikein. Meidän sähköpostiserverillä on osoitteet muotoa @jkl.hacklab.fi, joten tuo varoitus on aiheeton. Laitoin lähettäjän osoitteeksi no-reply@jkl.hacklab.fi mutta sitten oikeat mailiosoitteet tuohon `Reply-To`- ja `Mail-Followup-To`-kenttiin. Jos laittaa `From`-kenttään lähettäjän niin menee herkästi roskapostiin.

**Comment by zouppen** [comment]
@BFlorry eli nyt muuten kunnossa, saa kääntää englanniksi niin sitten valmis!

**Comment by zouppen** [comment]
Tunkiolta tuotantoon!
